export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const UI_RESET_ERROR = "UI_RESET_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOADING_ADVERTS = "LOADING_ADVERTS";
export const ADVERTS_LOADED = "ADVERTS_LOADED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
