export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const UI_RESET_ERROR = "UI_RESET_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOADING_ADVERTS = "LOADING_ADVERTS";
export const ADVERTS_LOADED = "ADVERTS_LOADED";

export const LOADING_ADVERT = "LOADING_ADVERT";
export const ADVERT_LOADED_SUCCESS = "ADVERT_LOADED_SUCCESS";
export const ADVERT_LOADED_FAILURE = "ADVERT_LOADED_FAILURE";

export const CREATE_AD_REQUEST = "CREATE_AD_REQUEST";
export const CREATE_AD_SUCCESS = "CREATE_AD_SUCCESS";
export const CREATE_AD_FAILURE = "CREATE_AD_FAILURE";
